ci: don't use urllib3 when testing old versions of Dulwich
It doesn't work, and causes exceptions like this:

  urllib3.exceptions.LocationValueError: No host specified.