ci: don't use urllib3 when testing old versions of Dulwich
It doesn't work, and causes exceptions like this:

  urllib3.exceptions.LocationValueError: No host specified.

--HG--
branch : 1.0.x
extra : absorb_source : 2e711eda4f5a5bf83e8f3ffd597dd08f1ea80531
extra : rebase_source : 4dc2c3ed7c8d40c9af2cad2a1fb2cfb005909ca5
extra : topic : compat