setup: in case of subprocess error in setuptools.setup(), print std{out,err}
This problem caused a hard to debug CI failure for ~9 months: setuptools.setup()
would call an "hg log" command, that would fail for a permission problem. The
information was not stored in the exception message, but in the captured stderr,
that was never printed.

A failure is now uglier, but more explicit:
```
+ exec python3.13 tests/run-tests.py '--color=always' --cover --xunit /builds/mercurial/hg-git/tests-3582275.xml
A CalledProcessError was raised:
Command '['hg', 'log', '-r', '.', '-T', '{node}\n{tag}\n{date|shortdate}']' returned non-zero exit status 255.
STDOUT:
=============
STDERR:
not trusting file /builds/mercurial/hg-git/.hg/hgrc from untrusted user root, group root
not trusting file /builds/mercurial/hg-git/.hg/hgrc from untrusted user root, group root
abort: Permission denied: '/builds/mercurial/hg-git/.hg/dirstate'  <-- THIS WAS THE MISSING INFORMATION
=============
Traceback (most recent call last):
[...]
subprocess.CalledProcessError: Command '['hg', 'log', '-r', '.', '-T', '{node}\n{tag}\n{date|shortdate}']' returned non-zero exit status 255.
```

--HG--
branch : 1.2.x
extra : histedit_source : b2a02de23151f60759544f25f7effab27f8169d2
extra : topic : debug-ci