compat: fix test-url-parsing.py
Before this commit, test-url-parsing.py was failing with the following error:

```
$ tests/run-tests.py --with-hg=<BASE>/venv3.14-hg721-dulwich025/bin/hg tests/test-url-parsing.py

Traceback (most recent call last):
  File "<BASE>/tests/test-url-parsing.py", line 113, in <module>
    tc.setUp()
    ~~~~~~~~^^
  File "<BASE>/tests/test-url-parsing.py", line 21, in setUp
    commands.init(ui.ui(), self.tmpdir)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: init() takes 0 positional arguments but 2 were given

ERROR: test-url-parsing.py output changed
!
Failed test-url-parsing.py: output changed and returned error code 1
```

The change was introduced in mercurial commit 43a67798b33a ("init: introduce a
new initialization system to explicitly load some module").

TODO:
- we could move the compat code in the test, since it is used only there
- we could use hasattr(mercurial.commands, "_init") instead of inspect

--HG--
extra : rebase_source : 24a1637088c8e43054d5c9bfd063f9cd5c6c67c4
extra : topic : hg-7.2