git_handler: use `self.ui.paths` instead of directly interpreting config
This correctly handles sub-options. Before, the test case failed with:
dulwich.errors.RefFormatError: refs/remotes/default:pushurl/beta