tests: demostrate crash on nonempty hg incoming when gitnode() is in template
If the user modified his log template to include gitnode(), an invocation of
hg incoming causes a crash with the following message:
    AttributeError: 'overlayrepo' object has no attribute 'githandler'

--HG--
extra : rebase_source : 528dc691ea73d3fbc9043954d1ba0f413f89b5b1
extra : topic : fix-hg-incoming