git_handler: use `self.ui.paths` instead of directly interpreting config
This correctly handles sub-options. Before, the test case failed with:
dulwich.errors.RefFormatError: refs/remotes/default:pushurl/beta

--HG--
extra : rebase_source : 94e2102e3e94194b41210673db16df42f107c074
extra : topic : pushurl