gitnodekw: do not crash on hg incoming when log template includes gitnode()
Before this change, if the user's log template included a call to gitnode() to
show the git commit hash, invoking "hg incoming" on a git repository that had at
least one incoming change failed with:

   AttributeError: 'overlayrepo' object has no attribute 'githandler'

Since an incoming changeset should already have well defined git commit hashes,
there is no apparent reason for which "hg incoming" should not have this
information already.

This change is a workaround that removes any reference to the hg-git structures
from the incoming changeset, thus merely avoiding the crash.

Fixes #239 (https://foss.heptapod.net/mercurial/hg-git/-/issues/239)

--HG--
extra : rebase_source : 8982ce683caf2faa7db2f9a68ae2d298d50f09f4
extra : topic : fix-hg-incoming